### ISSUE TITLE
Unable to install on OSx Homebridge Server

### ISSUE THREAD

**Issue by frodeaux** [planetbeing/homebridge-foscam-ng#1]
Tried installing this on my home bridge server running on OS X 10.12.1.  Received several warnings from npm, the main one being:

>  CXX(target) Release/obj.target/node-opus/src/node-opus.o
> ../src/node-opus.cc:41:1: warning: 'OpusEncoder' defined as a class here but
>       previously declared as a struct [-Wmismatched-tags]
> class OpusEncoder : public ObjectWrap {
> ^
> ../src/../deps/opus/include/opus.h:164:9: note: did you mean class here?
> typedef struct OpusEncoder OpusEncoder;
>         ^~~~~~
>         class
> 1 warning generated.
>   SOLINK_MODULE(target) Release/node-opus.node
> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

When home bridge starts it complains:

> :34:09 - ====================
> 16:34:09 - ERROR LOADING PLUGIN homebridge-foscam-ng:
> 16:34:09 - Error: Could not locate the bindings file. Tried:
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/build/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/build/Debug/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/build/Release/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/out/Debug/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/Debug/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/out/Release/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/Release/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/build/default/binding.node
>  → /usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/compiled/4.5.0/darwin/x64/binding.node
>     at bindings (/usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/bindings/bindings.js:88:9)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref/lib/ref.js:5:47)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/lib/struct.js:49:11)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/node_modules/ogg-packet/index.js:6:14)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-foscam-ng/node_modules/node-opus/lib/Encoder.js:4:18)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)

**Comment by planetbeing** [comment]
You may need to use the `--unsafe-perm` flag if you receive an error similar to this during installation:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.5.0"
```

**Comment by frodeaux** [comment]
That helped get a little further but once installed homebridge would not start  and has error

events.js:141

```
  throw er; // Unhandled 'error' event
  ^
```

Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TCP.onread (net.js:557:26)

**Comment by planetbeing** [comment]
Doesn't seem like it can find your Foscam. Check that your configuration is correct. In versions before v0.1.4, the port setting of the configuration was not properly propagated, so it wouldn't work on anything but port 88. If you have changed the port in the Foscam from the manufacturer default of 88, try updating this plugin to v0.1.4.

**Comment by planetbeing** [comment]
Reopen this if that didn't solve it.
