### ISSUE TITLE
Unable to view video FullScreen

### ISSUE THREAD

**Issue by ShawnMcCollum** [planetbeing/homebridge-foscam-ng#2]
When attempting to open the feed in its own window, the following error appears in homebridge.err

Wed, 28 Sep 2016 23:12:56 GMT rtsp-stream start-line sent SETUP rtsp://192.168.$
Wed, 28 Sep 2016 23:12:56 GMT rtsp-stream headers sent { Transport: 'RTP/AVP;un$
  CSeq: 3,
  Authorization: 'Digest username="admin", realm="Foscam IPCam Living Video", n$
Wed, 28 Sep 2016 23:12:57 GMT rtsp-stream decoding chunk 'RTSP/1.0 200 OK\r\nCS$
Wed, 28 Sep 2016 23:12:57 GMT rtsp-stream start of header
Wed, 28 Sep 2016 23:12:57 GMT rtsp-stream end of header
/usr/local/lib/node_modules/homebridge-foscam-ng/lib/RTSPClient.js:206
            if(addresses.length == 0) {
                        ^

TypeError: Cannot read property 'length' of undefined
/usr/local/lib/node_modules/homebridge-foscam-ng/lib/RTSPClient.js:206
            if(addresses.length == 0) {    at /usr/local/lib/node_modules/homeb$
    at QueryReqWrap.asyncCallback [as callback](dns.js:65:16)

The error also refers to an IP Address that does not refer to any device on my network.

**Comment by planetbeing** [comment]
1. What version of node are you using?
2. I need more context on those messages. All your lines are being cut off with $.

**Comment by planetbeing** [comment]
This should be fixed as of 72a61fc.
