### ISSUE TITLE
Foscam 9083P - Stream not working

### ISSUE THREAD

**Issue by zerolith** [planetbeing/homebridge-foscam-ng#5]
Hi,

I'm using the forementioned IP Cam, I have a little preview snapshot in Home-App and also receive any Motiondetection Message. But the Stream stays black, after couple of seconds I see in the error.log: 
Stop: rtsp://user:password@192.168.178.26:554/videoMain

Closing the Streaming-View and opening it up doesn't help.
This Message only appears once.

To my knowledge for this model API is running on Port 88. RTSP on 554

best regards
Daniel

**Comment by planetbeing** [comment]
I'd need the entire log to figure out what's going on.

**Comment by zerolith** [comment]
Can't reproduce right now, new Version is not starting up. I'll open another issue for you

**Comment by zerolith** [comment]
Upgraded` to 0.3.6 - Stream doesn't work (though snapshot is available )

`Mon, 10 Oct 2016 20:46:57 GMT Accessory [FI9803P] Processing characteristic set: [{"aid":1,"iid":22,"value":"ARBCUHeiZqFIsb42Rx5o1StvAxsBAQACDjE5Mi4xNjguMTc4LjIwAwIo1wQC8vsEBwIAAwABAQIFBwIAAwABAQI="}]
Mon, 10 Oct 2016 20:46:57 GMT Accessory [FI9803P] Setting Characteristic "Setup Endpoints" to value ARBCUHeiZqFIsb42Rx5o1StvAxsBAQACDjE5Mi4xNjguMTc4LjIwAwIo1wQC8vsEBwIAAwABAQIFBwIAAwABAQI=
Mon, 10 Oct 2016 20:46:57 GMT StreamController
Session:  <Buffer@0x25d07b2 42 50 77 a2 66 a1 48 b1 be 36 47 1e 68 d5 2b 6f>
ControllerAddress:  192.168.178.20
VideoPort:  55080
AudioPort:  64498
Video Crypto:  2
Video Master Key:  <Buffer@0x25d07e3 >
Video Master Salt:  <Buffer@0x25d07e5 >
Audio Crypto:  2
Audio Master Key:  <Buffer@0x25d07ec >
Audio Master Salt:  <Buffer@0x25d07ee >
(node:13700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: self.transcoderClass is not a constructor`

**Comment by planetbeing** [comment]
Could I get the full log starting from when Homebridge is started? There are some messages related to how the plugin is configuring itself that would be useful. It does report your Foscam username and password in the log so you could change those parts in the log if it makes you more comfortable.

Specifically, I'm looking for what it says in the log you configured the HTTP and RTSP ports to, what the plugin detected was the RTSP port (if anything), what happened when the plugin tried to connect and contact the RTSP port it detected or was configured.

**Comment by zerolith** [comment]
[10/10/2016, 9:49:07 PM] FoscamAccessory configured with daniel 192.168.178.26 88 3
[10/10/2016, 9:49:08 PM] FoscamAccessory: Date Synchronization { result: 0,
  timeSource: 0,
  ntpServer: 'Auto',
  dateFormat: 1,
  timeFormat: 1,
  timeZone: 0,
  isDst: 0,
  dst: 0,
  year: 2016,
  mon: 10,
  day: 10,
  hour: 21,
  minute: 49,
  sec: 4 } { timeSource: 0,
  ntpServer: 'Auto',
  dateFormat: 1,
  timeFormat: 1,
  timeZone: 0,
  isDst: 0,
  dst: 0,
  year: 2016,
  month: 9,
  day: 10,
  hour: 21,
  min: 49,
  sec: 8 }
[10/10/2016, 9:49:08 PM] Foscam Camera Info: { result: 0,
  productName: 'FI9803P+V2',
  serialNo: 1,
  devName: 'FI9803P',
  mac: '00626E67XXXX',
  year: 2016,
  mon: 10,
  day: 10,
  hour: 21,
  min: 49,
  sec: 4,
  timeZone: 0,
  firmwareVer: '2.54.2.37',
  hardwareVer: '1.9.3.17',
  pkgTime: '2016-07-30_11%3A50%3A02' } rtsp://daniel:password@192.168.178.26:554/videoMain rtsp://daniel:password@192.168.178.26:554/videoSub
[10/10/2016, 9:49:09 PM] FI9803P is running on port 41246.

**Comment by planetbeing** [comment]
And can you indeed access the RTSP stream via VLC at the specified URL: rtsp://daniel:password@192.168.178.26:554/videoMain ?

**Comment by zerolith** [comment]
That's working fine

**Comment by planetbeing** [comment]
Then I need the full log, running homebridge with the DEBUG=\* environmental variable.

**Comment by planetbeing** [comment]
Try v0.3.9 and see if it works for you. There was a problem with that model as well that some people on [this thread](https://github.com/luisiam/homebridge-foscamcamera/issues/6) were kind enough to help me diagnose.

**Comment by zerolith** [comment]
Sadly not yet: But with the new Version I have more Log to share:

Fri, 21 Oct 2016 08:34:48 GMT Accessory [FI9803P] Getting value for Characteristic "Supported RTP Configuration"
Fri, 21 Oct 2016 08:34:48 GMT Accessory [FI9803P] Got Characteristic "Supported RTP Configuration" value: AgEC
Fri, 21 Oct 2016 08:34:48 GMT Accessory [FI9803P] Getting value for Characteristic "Supported Video Stream Configuration"
Fri, 21 Oct 2016 08:34:48 GMT Accessory [FI9803P] Got Characteristic "Supported Video Stream Configuration" value: AbABAQACDwMBAAEBAQIBAAIBAQIBAgMLAQIABQICwAMDAR4DCwECAAUCAsADAwEPAwsBAgAFAgLQAgMBHgMLAQIABQIC0AIDAQ8DCwECgAICAuABAwEeAwsBAoACAgLgAQMBDwMLAQKAAgICaAEDAR4DCwECgAICAmgBAwEPAwsBAkABAgLwAAMBHgMLAQJAAQIC8AADAQ8DCwECQAECArQAAwEeAwsBAkABAgK0AAMBDw==
Fri, 21 Oct 2016 08:34:48 GMT Accessory [FI9803P] Getting value for Characteristic "Supported Audio Stream Configuration"
Fri, 21 Oct 2016 08:34:48 GMT Accessory [FI9803P] Got Characteristic "Supported Audio Stream Configuration" value: AQ4BAQMCCQEBAQIBAAMBAQIBAA==
Fri, 21 Oct 2016 08:34:48 GMT EventedHTTPServer [::ffff:192.168.178.70] HTTP Response is finished
Fri, 21 Oct 2016 08:34:49 GMT EventedHTTPServer [::ffff:192.168.178.70] HTTP request: /characteristics
Fri, 21 Oct 2016 08:34:49 GMT HAPServer [12:39:09:AC:C8:EA] HAP Request: PUT /characteristics
Fri, 21 Oct 2016 08:34:49 GMT Accessory [FI9803P] Processing characteristic set: [{"remote":true,"value":"ARDCL1mxr4xCT5VdqyUhgb+hAxsBAQACDjE5Mi4xNjguMTc4LjcwAwLq3wQC0dAEBwIAAwABAQIFBwIAAwABAQI=","aid":1,"iid":22}]
Fri, 21 Oct 2016 08:34:49 GMT Accessory [FI9803P] Setting Characteristic "Setup Endpoints" to value ARDCL1mxr4xCT5VdqyUhgb+hAxsBAQACDjE5Mi4xNjguMTc4LjcwAwLq3wQC0dAEBwIAAwABAQIFBwIAAwABAQI=
Fri, 21 Oct 2016 08:34:49 GMT StreamController
Session:  <Buffer@0x26da3aa c2 2f 59 b1 af 8c 42 4f 95 5d ab 25 21 81 bf a1>
ControllerAddress:  192.168.178.70
VideoPort:  57322
AudioPort:  53457
Video Crypto:  2
Video Master Key:  <Buffer@0x26da3db >
Video Master Salt:  <Buffer@0x26da3dd >
Audio Crypto:  2
Audio Master Key:  <Buffer@0x26da3e4 >
Audio Master Salt:  <Buffer@0x26da3e6 >
(node:7644) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: self.transcoderClass is not a constructor
