### ISSUE TITLE
Syntax Error in latest build ( 0.3.6 )

### ISSUE THREAD

**Issue by zerolith** [planetbeing/homebridge-foscam-ng#6]
Hi,

I upgraded to the latest build, but it seems that there's a SyntaxError. I couldn't locate it so far, I check the Syntax of all *.js files with "nodejs -c" and cannot find anything.

Hope anybody drops me in the right direction?

`[10/10/2016, 7:18:05 PM] ====================`
`[10/10/2016, 7:18:05 PM] ERROR LOADING PLUGIN homebridge-foscam-ng:`
`[10/10/2016, 7:18:05 PM] SyntaxError: Unexpected token =`
`at exports.runInThisContext (vm.js:53:16)`
`at Module._compile (module.js:373:25)`
`at Object.Module._extensions..js (module.js:416:10)`
`at Module.load (module.js:343:32)`
`at Function.Module._load (module.js:300:12)`
`at Module.require (module.js:353:17)`
`at require (internal/module.js:12:17)`
`at Object.<anonymous> (/root/.npm-global/lib/node_modules/homebridge-foscam-ng/node_modules/foscam-binary-client/index.js:6:26)`
`at Module._compile (module.js:409:26)`
`at Object.Module._extensions..js (module.js:416:10)`

I dropped everything and reinstalled Homebridge and homebridge-foscam-ng

**Comment by planetbeing** [comment]
What version of node are you running? I only test on 6.6.0.

**Comment by zerolith** [comment]
I'll try to upgrade Node - hang on

**Comment by zerolith** [comment]
Ok, this error is gone after upgrading from 5.X to 6.6.0.
